docs/src/pages/docs/features.en.mdx, docs/src/pages/docs/transition-event.en.mdx, packages/core/src/typeUtil.ts, packages/core/src/utils.ts
- Changed the JSDoc comments in the code from Korean to English.
- Translated the parts in the English version of the documentation that still contained Korean into English.
I believe that the use-funnel library is likely aimed at a global audience rather than just Korea. Therefore, I thought it was important to ensure that English is used consistently, which is why I undertook this task. Thank you for creating such a great library!
=> fix(docs, core): translated the Korean that needed to be expressed in English

README.md, docs/src/pages/docs/use-funnel.en.mdx, docs/src/pages/docs/use-funnel.ko.mdx, packages/core/src/core.ts, packages/core/src/useFunnel.tsx, packages/core/test/useFunnel.test.tsx
When transitioning to union type, if the type does not match the current type of staff, you will not be able to deduce the exact type. Also, some people would prefer to save the status of React's SetStateAction, but this was not considered.
Add a SetStateAction type that takes the current context in current step of a callback and specifies the context for the next step.
close #28
=> feat(core, docs): Add `SetStateAction` type of setting history context

docs/src/pages/docs/funnel-render.ko.mdx
Fixed missing characters in [funnel.Render](https://use-funnel.slash.page/ko/docs/funnel-render) Korean document.
```diff
- `funnel.Render />`는 퍼널의 각 <Keyword>step</Keyword>를 렌더링해요. 
+ `<funnel.Render />`는 퍼널의 각 <Keyword>step</Keyword>를 렌더링해요. 
```
=> docs: fix missing letter

docs/src/pages/docs/context-guide.ko.mdx
국문과 영문의 컨텐츠가 달라 하이라이팅 되어야할 부분이 잘못 표시된 것 같습니다!
아니면 영문과 동일하게 코드를 수정해도 괜찮을 것 같네요!
```tsx
const funnel = useFunnel({
id: "create-funnel-steps",
inital: {
step: "이메일입력",
context: {}
},
steps
});
```
=> chore(docs): createFunnelSteps로 정의하기 부분 하이라이팅 코드 블럭 위치 수정

docs/src/pages/docs/install.en.mdx
I fixed the link in the [docs - Installing](https://use-funnel.slash.page/docs/install) section for the `Next.js App Router`.
=> docs: fix the link

.changeset/kind-trains-care.md, packages/core/src/core.ts, packages/core/src/stepBuilder.ts, packages/core/src/useFunnel.tsx, packages/core/test/memoryRouter.ts, packages/core/test/stepBuilder.test.tsx
close #52
This issue is side effect from #49 . Fix `TPrevFunnelStepOption` generic type default assigned `FunnelStepGuardOption`
* Remove `FunnelStepBuilder` using with meta type (it should be verbose type hint by using `requiredKeys` option. meta option should be came back with new interface..)
* rename `FunnelStepBuilder` => `SimpleFunnelStepBuilder`
* add test case of current issue.
=> fix(core): when `createFunnelSteps` extends with no option at initial the context assigned never type.

packages/core/test/typeUtil.test-d.tsx
ISSUE https://github.com/toss/use-funnel/issues/57
=> test(core): add tests for OptionalCompareKeys when TResult has optional keys

README.md
- #60 
Updated the `SelectSchool` logic to correctly pass the `school parameter` into `history.push` by aligning the usage with the proper type expectations.
Ensured consistency with the SelectEmployee implementation, which did not exhibit the same error.
=> fix(docs): type error in SelectSchool within funnel.Render example from README.md

packages/react-router-dom/src/index.ts
```tsx
L74              [`${id}.histories}`]: [...(history ?? []).slice(0, currentIndex), state],
```
In line 74, after `${id}.histories`, there is a misplaced character `}` that causes an error in `history.replace` in @use-funnel/react-router-dom. I removed the character and defined the name of the searchParams as a variable(`stepName`, `contextName`, `historiesName`).
=> fix(react-router-dom): remove  the misplaced character }

.changeset/modern-moons-arrive.md, packages/core/src/useFunnel.tsx
add a fallback for funnel state when adapter history array is empty.
=> fix(core): add state initial fallback when history array is empty

.changeset/tame-adults-teach.md, packages/core/src/useFunnel.tsx, packages/next/src/index.ts, packages/next/test/index.test.tsx
close #67 
close #63 
* Change funnel state save architecture
* Using query string to save current step & context
* Using history.state to save "before histories"
=> fix(next): Keep current history context at refresh

docs/src/components/UseFunnelCodeBlock.tsx, docs/src/pages/docs/get-started.en.mdx, docs/src/pages/docs/get-started.ko.mdx, docs/src/pages/docs/sub-funnel.en.mdx, docs/src/pages/docs/sub-funnel.ko.mdx, docs/src/pages/docs/use-funnel.en.mdx, docs/src/pages/docs/use-funnel.ko.mdx
ISSUE: https://github.com/toss/use-funnel/issues/104
The English `funnel-render` page provides a tab view using the `UseFunnelCodeBlock` component. However, the Korean page does not. If this is an oversight, would it be acceptable to apply the `UseFunnelCodeBlock` component to the Korean `funnel-render` page as part of this PR?
=> feat(docs): add Documentation for Potential Hydration Issues with @use-funnel/browser in App Router

docs/src/pages/docs/custom-router.en.mdx, docs/src/pages/docs/custom-router.ko.mdx
Thanks for great library. 
I got error below following the current docs which is missing `cleanup` function on description. 
Fixing docs.
=> docs: add missing cleanup params on custom router

docs/src/components/UseFunnelCodeBlock.tsx
**description**
The UseFunnelImportReplace component had a bug where package names that were
substrings of other package names (e.g. 'react-router' in 'react-router-dom')
were being incorrectly replaced, resulting in invalid package names like 'react-router-dom-dom'
**Change Includes**
- Removes quotes from package path string
- Splits the path into segments
- Only replaces the exact package name match
- Replace for loop with Array.find() for better performance and readability
- Improve variable naming for better code clarity
**AS-IS**
**TO-BE**
=> fix(docs): prevent duplicate package name replacement in UseFunnelImportReplace

package.json
* The hash information (SHA) is not necessary for communication within the team or for managing change history. In fact, the version `pnpm@9.6.0` is sufficient to identify the specific version.
=> chore(package.json): simplify packageManager version

package.json
This PR removes the redundant `git add` command from the `lint-staged` configuration. Since `lint-staged` automatically works with files that are already staged, adding `git add` after running `prettier` and `eslint` is unnecessary.
* Removed the `git add` command from the `lint-staged` configuration.
* `git add` is not needed in this context because lint-staged operates on files that are already staged.
* This simplifies the configuration and avoids redundant operations.
=> chore(package.json): remove 'git add' command in 'lint-staged' configuration

docs/src/pages/docs/get-started.ko.mdx
=> docs: fix typo in ko docs

packages/core/src/stepBuilder.ts
Close: #133 
To allow steps to accept `readonly string[]` as an argument, I added `Readonly<TName[]>` to the type signature.
=> fix(core): allow createFunnelSteps.extends() to accept readonly string arrays as the first argument

docs/src/pages/docs/use-funnel.ko.mdx
This PR updates the tone of the `useFunnel` hook documentation by replacing formal expressions ("\~니다") with a more casual and friendly tone ("\~에요") for consistency.
* The documentation currently mixes formal and casual tones, which may feel inconsistent to readers.
* Since the majority of the document already uses the casual tone ("\~에요"), this change brings the remaining parts into alignment for a cohesive reading experience.
* Replaced all instances of "\~니다" with "\~에요".
* No semantic or structural changes were made to the content, only tone adjustments.
Thanks!
=> docs: unify useFunnel docs tone to casual ~에요 style

.changeset/hot-candles-drive.md, packages/next/src/useFunnel.tsx, packages/next/src/useNextRouter.ts, packages/next/src/util.ts, packages/next/test/index.test.tsx, packages/next/test/utils.tsx
Adds support for waiting for the isReady state of the Next.js router using the suspense option.
When suspense is set to true, the component must be wrapped in a Suspense boundary.
=> feature(next): add suspense option

packages/react-navigation-native/src/index.ts
Updated the code to resolve the related #162 .
=> fix(react-navigation-native): prevent navigation warning by skipping setParams on unfocused screens

.changeset/shaggy-insects-obey.md, docs/src/components/UseFunnelCodeBlock.tsx, docs/src/pages/docs/get-started.en.mdx, docs/src/pages/docs/get-started.ko.mdx, docs/src/pages/docs/install.en.mdx, docs/src/pages/docs/install.ko.mdx
Add App Router usage guide and client-only rendering example for @use-funnel/browser
|KO|EN|
|--|--|
|<img width="683" height="298" alt="스크린샷 2025-08-31 오후 11 46 07" src="https://github.com/user-attachments/assets/2b708f32-a733-4b27-b738-663bc89b6465" />|<img width="607" height="311" alt="스크린샷 2025-08-31 오후 11 45 57" src="https://github.com/user-attachments/assets/39788800-91f2-419f-bab3-d08bca236e48" />|
|KO|EN|
|--|--|
|<img width="675" height="787" alt="스크린샷 2025-08-31 오후 11 46 29" src="https://github.com/user-attachments/assets/aedefffd-5c6d-4130-874f-d4ec92a71b2f" />|<img width="660" height="801" alt="스크린샷 2025-08-31 오후 11 45 45" src="https://github.com/user-attachments/assets/389c5b65-faf6-44f7-9000-cb4784fff7f7" />|
=> feat(docs): Add App Router usage guide and client-only rendering example for @use-funnel/browser
